<?php
/**
 * Created by PhpStorm.
 * User: sylvain
 * Date: 07/03/18
 * Time: 18:20
 * PHP version 7
 */

namespace Model;

/**
 *
 */
class CharacterManager extends AbstractManager
{
    public function selectAll()
    {
        return parent::selectAll(); // TODO: Change the autogenerated stub
    }

    
}
